//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationStateKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationStateKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ValidationStateKeys", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a valid email address.
        /// </summary>
        internal static string ARTIST_EMAIL_ADDRESS_INVALID {
            get {
                return ResourceManager.GetString("ARTIST_EMAIL_ADDRESS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us your name.
        /// </summary>
        internal static string ARTIST_NEEDS_A_NAME {
            get {
                return ResourceManager.GetString("ARTIST_NEEDS_A_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a profile address.
        /// </summary>
        internal static string ARTIST_NEEDS_A_PROFILE_ADDRESS {
            get {
                return ResourceManager.GetString("ARTIST_NEEDS_A_PROFILE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a style.
        /// </summary>
        internal static string ARTIST_NEEDS_A_STYLE {
            get {
                return ResourceManager.GetString("ARTIST_NEEDS_A_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us your town.
        /// </summary>
        internal static string ARTIST_NEEDS_A_TOWN {
            get {
                return ResourceManager.GetString("ARTIST_NEEDS_A_TOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a profile address (should be letters and numbers only).
        /// </summary>
        internal static string ARTIST_PROFILE_ADDRESS_MUST_BE_ALPHA_NUMERIC {
            get {
                return ResourceManager.GetString("ARTIST_PROFILE_ADDRESS_MUST_BE_ALPHA_NUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This address has already been taken, sorry!.
        /// </summary>
        internal static string ARTIST_PROFILE_ADDRESS_MUST_BE_UNIQUE {
            get {
                return ResourceManager.GetString("ARTIST_PROFILE_ADDRESS_MUST_BE_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your comment.
        /// </summary>
        internal static string COMMENT_BODY_INVALID {
            get {
                return ResourceManager.GetString("COMMENT_BODY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We only accept images of type JPG or GIF.
        /// </summary>
        internal static string FILE_IS_NOT_AN_IMAGE {
            get {
                return ResourceManager.GetString("FILE_IS_NOT_AN_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gig description has to be less than 6000 characters.
        /// </summary>
        internal static string GIG_DESCRIPTION_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("GIG_DESCRIPTION_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gig name has to be less than 100 characters.
        /// </summary>
        internal static string GIG_NAME_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("GIG_NAME_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least one act.
        /// </summary>
        internal static string GIG_NEEDS_AT_LEAST_ONE_ACT {
            get {
                return ResourceManager.GetString("GIG_NEEDS_AT_LEAST_ONE_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your gig a name.
        /// </summary>
        internal static string GIG_NEEDS_A_NAME {
            get {
                return ResourceManager.GetString("GIG_NEEDS_A_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the venue your gig is at.
        /// </summary>
        internal static string GIG_NEEDS_A_VENUE {
            get {
                return ResourceManager.GetString("GIG_NEEDS_A_VENUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve given us too many words, sorry.
        /// </summary>
        internal static string NEWSITEM_BODY_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("NEWSITEM_BODY_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description has to be less than 200 characters.
        /// </summary>
        internal static string NEWSITEM_DESCRIPTION_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("NEWSITEM_DESCRIPTION_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The news headline has to be less than 50 characters.
        /// </summary>
        internal static string NEWSITEM_NAME_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("NEWSITEM_NAME_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your news some content.
        /// </summary>
        internal static string NEWSITEM_NEEDS_A_BODY {
            get {
                return ResourceManager.GetString("NEWSITEM_NEEDS_A_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your news a description.
        /// </summary>
        internal static string NEWSITEM_NEEDS_A_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEWSITEM_NEEDS_A_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your news a headline.
        /// </summary>
        internal static string NEWSITEM_NEEDS_A_NAME {
            get {
                return ResourceManager.GetString("NEWSITEM_NEEDS_A_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the band that wrote/recorded this music.
        /// </summary>
        internal static string TRACK_NEEDS_AN_ARTIST {
            get {
                return ResourceManager.GetString("TRACK_NEEDS_AN_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an MP3.
        /// </summary>
        internal static string TRACK_NEEDS_AN_MP3 {
            get {
                return ResourceManager.GetString("TRACK_NEEDS_AN_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your track a name.
        /// </summary>
        internal static string TRACK_NEEDS_A_NAME {
            get {
                return ResourceManager.GetString("TRACK_NEEDS_A_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your track a style.
        /// </summary>
        internal static string TRACK_NEEDS_A_STYLE {
            get {
                return ResourceManager.GetString("TRACK_NEEDS_A_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thats not an mp3! We can accept Mp3 files - sorry!.
        /// </summary>
        internal static string TRACK_NEEDS_A_VALID_MP3 {
            get {
                return ResourceManager.GetString("TRACK_NEEDS_A_VALID_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your forename has to be be less than 50 characters.
        /// </summary>
        internal static string USERPROFILE_FORENAME_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("USERPROFILE_FORENAME_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has to be be less than 1000 characters.
        /// </summary>
        internal static string USERPROFILE_PROFILE_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("USERPROFILE_PROFILE_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your surname has to be be less than 50 characters.
        /// </summary>
        internal static string USERPROFILE_SURNAME_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("USERPROFILE_SURNAME_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us your email address.
        /// </summary>
        internal static string USER_NEEDS_A_EMAILADDRESS {
            get {
                return ResourceManager.GetString("USER_NEEDS_A_EMAILADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        internal static string USER_NEEDS_A_PASSWORD {
            get {
                return ResourceManager.GetString("USER_NEEDS_A_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user has already registered with this email address.
        /// </summary>
        internal static string USER_NEEDS_A_UNIQUE_EMAILADDRESS {
            get {
                return ResourceManager.GetString("USER_NEEDS_A_UNIQUE_EMAILADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a username.
        /// </summary>
        internal static string USER_NEEDS_A_USERNAME {
            get {
                return ResourceManager.GetString("USER_NEEDS_A_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a valid email address.
        /// </summary>
        internal static string USER_NEEDS_A_VALID_EMAILADDRESS {
            get {
                return ResourceManager.GetString("USER_NEEDS_A_VALID_EMAILADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password is too short to be secure.
        /// </summary>
        internal static string USER_PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("USER_PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username is invalid.
        /// </summary>
        internal static string USER_USERNAME_INVALID {
            get {
                return ResourceManager.GetString("USER_USERNAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You username can only contain numbers and letters. No spaces please!.
        /// </summary>
        internal static string USER_USERNAME_MUST_BE_ALPHA_NUMERIC {
            get {
                return ResourceManager.GetString("USER_USERNAME_MUST_BE_ALPHA_NUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username is already taken.
        /// </summary>
        internal static string USER_USERNAME_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("USER_USERNAME_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username has to be at least 3 characters.
        /// </summary>
        internal static string USER_USERNAME_TOO_SHORT {
            get {
                return ResourceManager.GetString("USER_USERNAME_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your venue name has to be be less than 50 characters.
        /// </summary>
        internal static string VENUE_NAME_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("VENUE_NAME_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your venue a name.
        /// </summary>
        internal static string VENUE_NEEDS_NAME {
            get {
                return ResourceManager.GetString("VENUE_NEEDS_NAME", resourceCulture);
            }
        }
    }
}
